# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xUgp55rPEmuGgtJIdpVLRaxhwaHKfkHx
"""

from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()


class Notebook(BaseModel):
    text: str


notebooks = []


# Root Route
@app.get("/")
def home():
    return {"message": "Notebook API is running"}


# GET - Read all notebooks
@app.get("/notebooks")
def get_notebooks():
    return notebooks


# POST - Create a notebook
@app.post("/notebooks")
def add_notebook(notebook: Notebook):
    new_notebook = {
        "id": len(notebooks) + 1,
        "text": notebook.text
    }

    notebooks.append(new_notebook)
    return new_notebook


# PUT - Update a notebook
@app.put("/notebooks/{notebook_id}")
def update_notebook(notebook_id: int, notebook: Notebook):
    for item in notebooks:
        if item["id"] == notebook_id:
            item["text"] = notebook.text
            return item

    return {"message": "Notebook not found"}


# DELETE - Delete a notebook
@app.delete("/notebooks/{notebook_id}")
def delete_notebook(notebook_id: int):
    for item in notebooks:
        if item["id"] == notebook_id:
            notebooks.remove(item)
            return {"message": "Notebook deleted"}

    return {"message": "Notebook not found"}

{
    "text": "Learn FastAPI"
}

